import type { Component } from "vue"
import {
  AccessibilityOutline,
  AddCircleOutline,
  AddOutline,
  AirplaneOutline,
  AlarmOutline,
  AlbumsOutline,
  AlertCircleOutline,
  AlertOutline,
  AmericanFootballOutline,
  AnalyticsOutline,
  ApertureOutline,
  AppsOutline,
  ArchiveOutline,
  ArrowBackCircleOutline,
  ArrowBackOutline,
  ArrowDownCircleOutline,
  ArrowDownOutline,
  ArrowForwardCircleOutline,
  ArrowForwardOutline,
  ArrowRedoCircleOutline,
  ArrowRedoOutline,
  ArrowUndoCircleOutline,
  ArrowUndoOutline,
  ArrowUpCircleOutline,
  ArrowUpOutline,
  AtCircleOutline,
  AtOutline,
  AttachOutline,
  BackspaceOutline,
  BagAddOutline,
  BagCheckOutline,
  BagHandleOutline,
  BagOutline,
  BagRemoveOutline,
  BalloonOutline,
  BanOutline,
  BandageOutline,
  BarChartOutline,
  BarbellOutline,
  BarcodeOutline,
  BaseballOutline,
  BasketOutline,
  BasketballOutline,
  BatteryChargingOutline,
  BatteryDeadOutline,
  BatteryFullOutline,
  BatteryHalfOutline,
  BeakerOutline,
  BedOutline,
  BeerOutline,
  BicycleOutline,
  BluetoothOutline,
  BoatOutline,
  BodyOutline,
  BonfireOutline,
  BookOutline,
  BookmarkOutline,
  BookmarksOutline,
  BowlingBallOutline,
  BriefcaseOutline,
  BrowsersOutline,
  BrushOutline,
  BugOutline,
  BuildOutline,
  BulbOutline,
  BusOutline,
  BusinessOutline,
  CafeOutline,
  CalculatorOutline,
  CalendarClearOutline,
  CalendarNumberOutline,
  CalendarOutline,
  CallOutline,
  CameraOutline,
  CameraReverseOutline,
  CarOutline,
  CarSportOutline,
  CardOutline,
  CaretBackCircleOutline,
  CaretBackOutline,
  CaretDownCircleOutline,
  CaretDownOutline,
  CaretForwardCircleOutline,
  CaretForwardOutline,
  CaretUpCircleOutline,
  CaretUpOutline,
  CartOutline,
  CashOutline,
  CellularOutline,
  ChatboxEllipsesOutline,
  ChatboxOutline,
  ChatbubbleEllipsesOutline,
  ChatbubbleOutline,
  ChatbubblesOutline,
  CheckboxOutline,
  CheckmarkCircleOutline,
  CheckmarkDoneCircleOutline,
  CheckmarkDoneOutline,
  CheckmarkOutline,
  ChevronBackCircleOutline,
  ChevronBackOutline,
  ChevronDownCircleOutline,
  ChevronDownOutline,
  ChevronForwardCircleOutline,
  ChevronForwardOutline,
  ChevronUpCircleOutline,
  ChevronUpOutline,
  ClipboardOutline,
  CloseCircleOutline,
  CloseOutline,
  CloudCircleOutline,
  CloudDoneOutline,
  CloudDownloadOutline,
  CloudOfflineOutline,
  CloudOutline,
  CloudUploadOutline,
  CloudyNightOutline,
  CloudyOutline,
  CodeDownloadOutline,
  CodeOutline,
  CodeSlashOutline,
  CodeWorkingOutline,
  CogOutline,
  ColorFillOutline,
  ColorFilterOutline,
  ColorPaletteOutline,
  ColorWandOutline,
  CompassOutline,
  ConstructOutline,
  ContractOutline,
  ContrastOutline,
  CopyOutline,
  CreateOutline,
  CropOutline,
  CubeOutline,
  CutOutline,
  DesktopOutline,
  DiamondOutline,
  DiceOutline,
  DiscOutline,
  DocumentAttachOutline,
  DocumentLockOutline,
  DocumentOutline,
  DocumentTextOutline,
  DocumentsOutline,
  DownloadOutline,
  DuplicateOutline,
  EarOutline,
  EarthOutline,
  EaselOutline,
  EggOutline,
  EllipseOutline,
  EllipsisHorizontalCircleOutline,
  EllipsisHorizontalOutline,
  EllipsisVerticalCircleOutline,
  EllipsisVerticalOutline,
  EnterOutline,
  ExitOutline,
  ExpandOutline,
  ExtensionPuzzleOutline,
  EyeOffOutline,
  EyeOutline,
  EyedropOutline,
  FastFoodOutline,
  FemaleOutline,
  FileTrayFullOutline,
  FileTrayOutline,
  FileTrayStackedOutline,
  FilmOutline,
  FilterCircleOutline,
  FilterOutline,
  FingerPrintOutline,
  FishOutline,
  FitnessOutline,
  FlagOutline,
  FlameOutline,
  FlashOffOutline,
  FlashOutline,
  FlashlightOutline,
  FlaskOutline,
  FlowerOutline,
  FolderOpenOutline,
  FolderOutline,
  FootballOutline,
  FootstepsOutline,
  FunnelOutline,
  GameControllerOutline,
  GiftOutline,
  GitBranchOutline,
  GitCommitOutline,
  GitCompareOutline,
  GitMergeOutline,
  GitNetworkOutline,
  GitPullRequestOutline,
  GlassesOutline,
  GlobeOutline,
  GolfOutline,
  GridOutline,
  HammerOutline,
  HandLeftOutline,
  HandRightOutline,
  HappyOutline,
  HardwareChipOutline,
  HeadsetOutline,
  HeartCircleOutline,
  HeartDislikeCircleOutline,
  HeartDislikeOutline,
  HeartHalfOutline,
  HeartOutline,
  HelpBuoyOutline,
  HelpCircleOutline,
  HelpOutline,
  HomeOutline,
  HourglassOutline,
  IceCreamOutline,
  IdCardOutline,
  ImageOutline,
  ImagesOutline,
  InfiniteOutline,
  InformationCircleOutline,
  InformationOutline,
  InvertModeOutline,
  JournalOutline,
  KeyOutline,
  KeypadOutline,
  LanguageOutline,
  LaptopOutline,
  LayersOutline,
  LeafOutline,
  LibraryOutline,
  LinkOutline,
  ListCircleOutline,
  ListOutline,
  LocateOutline,
  LocationOutline,
  LockClosedOutline,
  LockOpenOutline,
  LogInOutline,
  LogOutOutline,
  MagnetOutline,
  MailOpenOutline,
  MailOutline,
  MailUnreadOutline,
  MaleFemaleOutline,
  MaleOutline,
  ManOutline,
  MapOutline,
  MedalOutline,
  MedicalOutline,
  MedkitOutline,
  MegaphoneOutline,
  MenuOutline,
  MicCircleOutline,
  MicOffCircleOutline,
  MicOffOutline,
  MicOutline,
  MoonOutline,
  MoveOutline,
  MusicalNoteOutline,
  MusicalNotesOutline,
  NavigateCircleOutline,
  NavigateOutline,
  NewspaperOutline,
  NotificationsCircleOutline,
  NotificationsOffCircleOutline,
  NotificationsOffOutline,
  NotificationsOutline,
  NuclearOutline,
  NutritionOutline,
  OpenOutline,
  OptionsOutline,
  PaperPlaneOutline,
  PartlySunnyOutline,
  PauseCircleOutline,
  PauseOutline,
  PawOutline,
  PencilOutline,
  PeopleCircleOutline,
  PeopleOutline,
  PersonAddOutline,
  PersonCircleOutline,
  PersonOutline,
  PersonRemoveOutline,
  PhoneLandscapeOutline,
  PhonePortraitOutline,
  PieChartOutline,
  PinOutline,
  PintOutline,
  PizzaOutline,
  PlanetOutline,
  PlayBackCircleOutline,
  PlayBackOutline,
  PlayCircleOutline,
  PlayForwardCircleOutline,
  PlayForwardOutline,
  PlayOutline,
  PlaySkipBackCircleOutline,
  PlaySkipBackOutline,
  PlaySkipForwardCircleOutline,
  PlaySkipForwardOutline,
  PodiumOutline,
  PowerOutline,
  PricetagOutline,
  PricetagsOutline,
  PrintOutline,
  PrismOutline,
  PulseOutline,
  PushOutline,
  QrCodeOutline,
  RadioButtonOffOutline,
  RadioButtonOnOutline,
  RadioOutline,
  RainyOutline,
  ReaderOutline,
  ReceiptOutline,
  RecordingOutline,
  RefreshCircleOutline,
  RefreshOutline,
  ReloadCircleOutline,
  ReloadOutline,
  RemoveCircleOutline,
  RemoveOutline,
  ReorderFourOutline,
  ReorderThreeOutline,
  ReorderTwoOutline,
  RepeatOutline,
  ResizeOutline,
  RestaurantOutline,
  ReturnDownBackOutline,
  ReturnDownForwardOutline,
  ReturnUpBackOutline,
  ReturnUpForwardOutline,
  RibbonOutline,
  RocketOutline,
  RoseOutline,
  SadOutline,
  SaveOutline,
  ScaleOutline,
  ScanCircleOutline,
  ScanOutline,
  SchoolOutline,
  SearchCircleOutline,
  SearchOutline,
  SendOutline,
  ServerOutline,
  SettingsOutline,
  ShapesOutline,
  ShareOutline,
  ShareSocialOutline,
  ShieldCheckmarkOutline,
  ShieldHalfOutline,
  ShieldOutline,
  ShirtOutline,
  ShuffleOutline,
  SkullOutline,
  SnowOutline,
  SparklesOutline,
  SpeedometerOutline,
  SquareOutline,
  StarHalfOutline,
  StarOutline,
  StatsChartOutline,
  StopCircleOutline,
  StopOutline,
  StopwatchOutline,
  StorefrontOutline,
  SubwayOutline,
  SunnyOutline,
  SwapHorizontalOutline,
  SwapVerticalOutline,
  SyncCircleOutline,
  SyncOutline,
  TabletLandscapeOutline,
  TabletPortraitOutline,
  TelescopeOutline,
  TennisballOutline,
  TerminalOutline,
  TextOutline,
  ThermometerOutline,
  ThumbsDownOutline,
  ThumbsUpOutline,
  ThunderstormOutline,
  TicketOutline,
  TimeOutline,
  TimerOutline,
  TodayOutline,
  ToggleOutline,
  TrailSignOutline,
  TrainOutline,
  TransgenderOutline,
  TrashBinOutline,
  TrashOutline,
  TrendingDownOutline,
  TrendingUpOutline,
  TriangleOutline,
  TrophyOutline,
  TvOutline,
  UmbrellaOutline,
  UnlinkOutline,
  VideocamOffOutline,
  VideocamOutline,
  VolumeHighOutline,
  VolumeLowOutline,
  VolumeMediumOutline,
  VolumeMuteOutline,
  VolumeOffOutline,
  WalkOutline,
  WalletOutline,
  WarningOutline,
  WatchOutline,
  WaterOutline,
  WifiOutline,
  WineOutline,
  WomanOutline,
} from "@vicons/ionicons5"

// 图标目录：@vicons/ionicons5 全部 Outline 系列（由脚本生成，勿手改）。
// 显式命名导入以保持 tree-shaking（namespace 导入会打包全部 1332 个图标）。
export const iconCatalog: { name: string; component: Component }[] = [
  { name: "AccessibilityOutline", component: AccessibilityOutline },
  { name: "AddCircleOutline", component: AddCircleOutline },
  { name: "AddOutline", component: AddOutline },
  { name: "AirplaneOutline", component: AirplaneOutline },
  { name: "AlarmOutline", component: AlarmOutline },
  { name: "AlbumsOutline", component: AlbumsOutline },
  { name: "AlertCircleOutline", component: AlertCircleOutline },
  { name: "AlertOutline", component: AlertOutline },
  { name: "AmericanFootballOutline", component: AmericanFootballOutline },
  { name: "AnalyticsOutline", component: AnalyticsOutline },
  { name: "ApertureOutline", component: ApertureOutline },
  { name: "AppsOutline", component: AppsOutline },
  { name: "ArchiveOutline", component: ArchiveOutline },
  { name: "ArrowBackCircleOutline", component: ArrowBackCircleOutline },
  { name: "ArrowBackOutline", component: ArrowBackOutline },
  { name: "ArrowDownCircleOutline", component: ArrowDownCircleOutline },
  { name: "ArrowDownOutline", component: ArrowDownOutline },
  { name: "ArrowForwardCircleOutline", component: ArrowForwardCircleOutline },
  { name: "ArrowForwardOutline", component: ArrowForwardOutline },
  { name: "ArrowRedoCircleOutline", component: ArrowRedoCircleOutline },
  { name: "ArrowRedoOutline", component: ArrowRedoOutline },
  { name: "ArrowUndoCircleOutline", component: ArrowUndoCircleOutline },
  { name: "ArrowUndoOutline", component: ArrowUndoOutline },
  { name: "ArrowUpCircleOutline", component: ArrowUpCircleOutline },
  { name: "ArrowUpOutline", component: ArrowUpOutline },
  { name: "AtCircleOutline", component: AtCircleOutline },
  { name: "AtOutline", component: AtOutline },
  { name: "AttachOutline", component: AttachOutline },
  { name: "BackspaceOutline", component: BackspaceOutline },
  { name: "BagAddOutline", component: BagAddOutline },
  { name: "BagCheckOutline", component: BagCheckOutline },
  { name: "BagHandleOutline", component: BagHandleOutline },
  { name: "BagOutline", component: BagOutline },
  { name: "BagRemoveOutline", component: BagRemoveOutline },
  { name: "BalloonOutline", component: BalloonOutline },
  { name: "BanOutline", component: BanOutline },
  { name: "BandageOutline", component: BandageOutline },
  { name: "BarChartOutline", component: BarChartOutline },
  { name: "BarbellOutline", component: BarbellOutline },
  { name: "BarcodeOutline", component: BarcodeOutline },
  { name: "BaseballOutline", component: BaseballOutline },
  { name: "BasketOutline", component: BasketOutline },
  { name: "BasketballOutline", component: BasketballOutline },
  { name: "BatteryChargingOutline", component: BatteryChargingOutline },
  { name: "BatteryDeadOutline", component: BatteryDeadOutline },
  { name: "BatteryFullOutline", component: BatteryFullOutline },
  { name: "BatteryHalfOutline", component: BatteryHalfOutline },
  { name: "BeakerOutline", component: BeakerOutline },
  { name: "BedOutline", component: BedOutline },
  { name: "BeerOutline", component: BeerOutline },
  { name: "BicycleOutline", component: BicycleOutline },
  { name: "BluetoothOutline", component: BluetoothOutline },
  { name: "BoatOutline", component: BoatOutline },
  { name: "BodyOutline", component: BodyOutline },
  { name: "BonfireOutline", component: BonfireOutline },
  { name: "BookOutline", component: BookOutline },
  { name: "BookmarkOutline", component: BookmarkOutline },
  { name: "BookmarksOutline", component: BookmarksOutline },
  { name: "BowlingBallOutline", component: BowlingBallOutline },
  { name: "BriefcaseOutline", component: BriefcaseOutline },
  { name: "BrowsersOutline", component: BrowsersOutline },
  { name: "BrushOutline", component: BrushOutline },
  { name: "BugOutline", component: BugOutline },
  { name: "BuildOutline", component: BuildOutline },
  { name: "BulbOutline", component: BulbOutline },
  { name: "BusOutline", component: BusOutline },
  { name: "BusinessOutline", component: BusinessOutline },
  { name: "CafeOutline", component: CafeOutline },
  { name: "CalculatorOutline", component: CalculatorOutline },
  { name: "CalendarClearOutline", component: CalendarClearOutline },
  { name: "CalendarNumberOutline", component: CalendarNumberOutline },
  { name: "CalendarOutline", component: CalendarOutline },
  { name: "CallOutline", component: CallOutline },
  { name: "CameraOutline", component: CameraOutline },
  { name: "CameraReverseOutline", component: CameraReverseOutline },
  { name: "CarOutline", component: CarOutline },
  { name: "CarSportOutline", component: CarSportOutline },
  { name: "CardOutline", component: CardOutline },
  { name: "CaretBackCircleOutline", component: CaretBackCircleOutline },
  { name: "CaretBackOutline", component: CaretBackOutline },
  { name: "CaretDownCircleOutline", component: CaretDownCircleOutline },
  { name: "CaretDownOutline", component: CaretDownOutline },
  { name: "CaretForwardCircleOutline", component: CaretForwardCircleOutline },
  { name: "CaretForwardOutline", component: CaretForwardOutline },
  { name: "CaretUpCircleOutline", component: CaretUpCircleOutline },
  { name: "CaretUpOutline", component: CaretUpOutline },
  { name: "CartOutline", component: CartOutline },
  { name: "CashOutline", component: CashOutline },
  { name: "CellularOutline", component: CellularOutline },
  { name: "ChatboxEllipsesOutline", component: ChatboxEllipsesOutline },
  { name: "ChatboxOutline", component: ChatboxOutline },
  { name: "ChatbubbleEllipsesOutline", component: ChatbubbleEllipsesOutline },
  { name: "ChatbubbleOutline", component: ChatbubbleOutline },
  { name: "ChatbubblesOutline", component: ChatbubblesOutline },
  { name: "CheckboxOutline", component: CheckboxOutline },
  { name: "CheckmarkCircleOutline", component: CheckmarkCircleOutline },
  { name: "CheckmarkDoneCircleOutline", component: CheckmarkDoneCircleOutline },
  { name: "CheckmarkDoneOutline", component: CheckmarkDoneOutline },
  { name: "CheckmarkOutline", component: CheckmarkOutline },
  { name: "ChevronBackCircleOutline", component: ChevronBackCircleOutline },
  { name: "ChevronBackOutline", component: ChevronBackOutline },
  { name: "ChevronDownCircleOutline", component: ChevronDownCircleOutline },
  { name: "ChevronDownOutline", component: ChevronDownOutline },
  { name: "ChevronForwardCircleOutline", component: ChevronForwardCircleOutline },
  { name: "ChevronForwardOutline", component: ChevronForwardOutline },
  { name: "ChevronUpCircleOutline", component: ChevronUpCircleOutline },
  { name: "ChevronUpOutline", component: ChevronUpOutline },
  { name: "ClipboardOutline", component: ClipboardOutline },
  { name: "CloseCircleOutline", component: CloseCircleOutline },
  { name: "CloseOutline", component: CloseOutline },
  { name: "CloudCircleOutline", component: CloudCircleOutline },
  { name: "CloudDoneOutline", component: CloudDoneOutline },
  { name: "CloudDownloadOutline", component: CloudDownloadOutline },
  { name: "CloudOfflineOutline", component: CloudOfflineOutline },
  { name: "CloudOutline", component: CloudOutline },
  { name: "CloudUploadOutline", component: CloudUploadOutline },
  { name: "CloudyNightOutline", component: CloudyNightOutline },
  { name: "CloudyOutline", component: CloudyOutline },
  { name: "CodeDownloadOutline", component: CodeDownloadOutline },
  { name: "CodeOutline", component: CodeOutline },
  { name: "CodeSlashOutline", component: CodeSlashOutline },
  { name: "CodeWorkingOutline", component: CodeWorkingOutline },
  { name: "CogOutline", component: CogOutline },
  { name: "ColorFillOutline", component: ColorFillOutline },
  { name: "ColorFilterOutline", component: ColorFilterOutline },
  { name: "ColorPaletteOutline", component: ColorPaletteOutline },
  { name: "ColorWandOutline", component: ColorWandOutline },
  { name: "CompassOutline", component: CompassOutline },
  { name: "ConstructOutline", component: ConstructOutline },
  { name: "ContractOutline", component: ContractOutline },
  { name: "ContrastOutline", component: ContrastOutline },
  { name: "CopyOutline", component: CopyOutline },
  { name: "CreateOutline", component: CreateOutline },
  { name: "CropOutline", component: CropOutline },
  { name: "CubeOutline", component: CubeOutline },
  { name: "CutOutline", component: CutOutline },
  { name: "DesktopOutline", component: DesktopOutline },
  { name: "DiamondOutline", component: DiamondOutline },
  { name: "DiceOutline", component: DiceOutline },
  { name: "DiscOutline", component: DiscOutline },
  { name: "DocumentAttachOutline", component: DocumentAttachOutline },
  { name: "DocumentLockOutline", component: DocumentLockOutline },
  { name: "DocumentOutline", component: DocumentOutline },
  { name: "DocumentTextOutline", component: DocumentTextOutline },
  { name: "DocumentsOutline", component: DocumentsOutline },
  { name: "DownloadOutline", component: DownloadOutline },
  { name: "DuplicateOutline", component: DuplicateOutline },
  { name: "EarOutline", component: EarOutline },
  { name: "EarthOutline", component: EarthOutline },
  { name: "EaselOutline", component: EaselOutline },
  { name: "EggOutline", component: EggOutline },
  { name: "EllipseOutline", component: EllipseOutline },
  { name: "EllipsisHorizontalCircleOutline", component: EllipsisHorizontalCircleOutline },
  { name: "EllipsisHorizontalOutline", component: EllipsisHorizontalOutline },
  { name: "EllipsisVerticalCircleOutline", component: EllipsisVerticalCircleOutline },
  { name: "EllipsisVerticalOutline", component: EllipsisVerticalOutline },
  { name: "EnterOutline", component: EnterOutline },
  { name: "ExitOutline", component: ExitOutline },
  { name: "ExpandOutline", component: ExpandOutline },
  { name: "ExtensionPuzzleOutline", component: ExtensionPuzzleOutline },
  { name: "EyeOffOutline", component: EyeOffOutline },
  { name: "EyeOutline", component: EyeOutline },
  { name: "EyedropOutline", component: EyedropOutline },
  { name: "FastFoodOutline", component: FastFoodOutline },
  { name: "FemaleOutline", component: FemaleOutline },
  { name: "FileTrayFullOutline", component: FileTrayFullOutline },
  { name: "FileTrayOutline", component: FileTrayOutline },
  { name: "FileTrayStackedOutline", component: FileTrayStackedOutline },
  { name: "FilmOutline", component: FilmOutline },
  { name: "FilterCircleOutline", component: FilterCircleOutline },
  { name: "FilterOutline", component: FilterOutline },
  { name: "FingerPrintOutline", component: FingerPrintOutline },
  { name: "FishOutline", component: FishOutline },
  { name: "FitnessOutline", component: FitnessOutline },
  { name: "FlagOutline", component: FlagOutline },
  { name: "FlameOutline", component: FlameOutline },
  { name: "FlashOffOutline", component: FlashOffOutline },
  { name: "FlashOutline", component: FlashOutline },
  { name: "FlashlightOutline", component: FlashlightOutline },
  { name: "FlaskOutline", component: FlaskOutline },
  { name: "FlowerOutline", component: FlowerOutline },
  { name: "FolderOpenOutline", component: FolderOpenOutline },
  { name: "FolderOutline", component: FolderOutline },
  { name: "FootballOutline", component: FootballOutline },
  { name: "FootstepsOutline", component: FootstepsOutline },
  { name: "FunnelOutline", component: FunnelOutline },
  { name: "GameControllerOutline", component: GameControllerOutline },
  { name: "GiftOutline", component: GiftOutline },
  { name: "GitBranchOutline", component: GitBranchOutline },
  { name: "GitCommitOutline", component: GitCommitOutline },
  { name: "GitCompareOutline", component: GitCompareOutline },
  { name: "GitMergeOutline", component: GitMergeOutline },
  { name: "GitNetworkOutline", component: GitNetworkOutline },
  { name: "GitPullRequestOutline", component: GitPullRequestOutline },
  { name: "GlassesOutline", component: GlassesOutline },
  { name: "GlobeOutline", component: GlobeOutline },
  { name: "GolfOutline", component: GolfOutline },
  { name: "GridOutline", component: GridOutline },
  { name: "HammerOutline", component: HammerOutline },
  { name: "HandLeftOutline", component: HandLeftOutline },
  { name: "HandRightOutline", component: HandRightOutline },
  { name: "HappyOutline", component: HappyOutline },
  { name: "HardwareChipOutline", component: HardwareChipOutline },
  { name: "HeadsetOutline", component: HeadsetOutline },
  { name: "HeartCircleOutline", component: HeartCircleOutline },
  { name: "HeartDislikeCircleOutline", component: HeartDislikeCircleOutline },
  { name: "HeartDislikeOutline", component: HeartDislikeOutline },
  { name: "HeartHalfOutline", component: HeartHalfOutline },
  { name: "HeartOutline", component: HeartOutline },
  { name: "HelpBuoyOutline", component: HelpBuoyOutline },
  { name: "HelpCircleOutline", component: HelpCircleOutline },
  { name: "HelpOutline", component: HelpOutline },
  { name: "HomeOutline", component: HomeOutline },
  { name: "HourglassOutline", component: HourglassOutline },
  { name: "IceCreamOutline", component: IceCreamOutline },
  { name: "IdCardOutline", component: IdCardOutline },
  { name: "ImageOutline", component: ImageOutline },
  { name: "ImagesOutline", component: ImagesOutline },
  { name: "InfiniteOutline", component: InfiniteOutline },
  { name: "InformationCircleOutline", component: InformationCircleOutline },
  { name: "InformationOutline", component: InformationOutline },
  { name: "InvertModeOutline", component: InvertModeOutline },
  { name: "JournalOutline", component: JournalOutline },
  { name: "KeyOutline", component: KeyOutline },
  { name: "KeypadOutline", component: KeypadOutline },
  { name: "LanguageOutline", component: LanguageOutline },
  { name: "LaptopOutline", component: LaptopOutline },
  { name: "LayersOutline", component: LayersOutline },
  { name: "LeafOutline", component: LeafOutline },
  { name: "LibraryOutline", component: LibraryOutline },
  { name: "LinkOutline", component: LinkOutline },
  { name: "ListCircleOutline", component: ListCircleOutline },
  { name: "ListOutline", component: ListOutline },
  { name: "LocateOutline", component: LocateOutline },
  { name: "LocationOutline", component: LocationOutline },
  { name: "LockClosedOutline", component: LockClosedOutline },
  { name: "LockOpenOutline", component: LockOpenOutline },
  { name: "LogInOutline", component: LogInOutline },
  { name: "LogOutOutline", component: LogOutOutline },
  { name: "MagnetOutline", component: MagnetOutline },
  { name: "MailOpenOutline", component: MailOpenOutline },
  { name: "MailOutline", component: MailOutline },
  { name: "MailUnreadOutline", component: MailUnreadOutline },
  { name: "MaleFemaleOutline", component: MaleFemaleOutline },
  { name: "MaleOutline", component: MaleOutline },
  { name: "ManOutline", component: ManOutline },
  { name: "MapOutline", component: MapOutline },
  { name: "MedalOutline", component: MedalOutline },
  { name: "MedicalOutline", component: MedicalOutline },
  { name: "MedkitOutline", component: MedkitOutline },
  { name: "MegaphoneOutline", component: MegaphoneOutline },
  { name: "MenuOutline", component: MenuOutline },
  { name: "MicCircleOutline", component: MicCircleOutline },
  { name: "MicOffCircleOutline", component: MicOffCircleOutline },
  { name: "MicOffOutline", component: MicOffOutline },
  { name: "MicOutline", component: MicOutline },
  { name: "MoonOutline", component: MoonOutline },
  { name: "MoveOutline", component: MoveOutline },
  { name: "MusicalNoteOutline", component: MusicalNoteOutline },
  { name: "MusicalNotesOutline", component: MusicalNotesOutline },
  { name: "NavigateCircleOutline", component: NavigateCircleOutline },
  { name: "NavigateOutline", component: NavigateOutline },
  { name: "NewspaperOutline", component: NewspaperOutline },
  { name: "NotificationsCircleOutline", component: NotificationsCircleOutline },
  { name: "NotificationsOffCircleOutline", component: NotificationsOffCircleOutline },
  { name: "NotificationsOffOutline", component: NotificationsOffOutline },
  { name: "NotificationsOutline", component: NotificationsOutline },
  { name: "NuclearOutline", component: NuclearOutline },
  { name: "NutritionOutline", component: NutritionOutline },
  { name: "OpenOutline", component: OpenOutline },
  { name: "OptionsOutline", component: OptionsOutline },
  { name: "PaperPlaneOutline", component: PaperPlaneOutline },
  { name: "PartlySunnyOutline", component: PartlySunnyOutline },
  { name: "PauseCircleOutline", component: PauseCircleOutline },
  { name: "PauseOutline", component: PauseOutline },
  { name: "PawOutline", component: PawOutline },
  { name: "PencilOutline", component: PencilOutline },
  { name: "PeopleCircleOutline", component: PeopleCircleOutline },
  { name: "PeopleOutline", component: PeopleOutline },
  { name: "PersonAddOutline", component: PersonAddOutline },
  { name: "PersonCircleOutline", component: PersonCircleOutline },
  { name: "PersonOutline", component: PersonOutline },
  { name: "PersonRemoveOutline", component: PersonRemoveOutline },
  { name: "PhoneLandscapeOutline", component: PhoneLandscapeOutline },
  { name: "PhonePortraitOutline", component: PhonePortraitOutline },
  { name: "PieChartOutline", component: PieChartOutline },
  { name: "PinOutline", component: PinOutline },
  { name: "PintOutline", component: PintOutline },
  { name: "PizzaOutline", component: PizzaOutline },
  { name: "PlanetOutline", component: PlanetOutline },
  { name: "PlayBackCircleOutline", component: PlayBackCircleOutline },
  { name: "PlayBackOutline", component: PlayBackOutline },
  { name: "PlayCircleOutline", component: PlayCircleOutline },
  { name: "PlayForwardCircleOutline", component: PlayForwardCircleOutline },
  { name: "PlayForwardOutline", component: PlayForwardOutline },
  { name: "PlayOutline", component: PlayOutline },
  { name: "PlaySkipBackCircleOutline", component: PlaySkipBackCircleOutline },
  { name: "PlaySkipBackOutline", component: PlaySkipBackOutline },
  { name: "PlaySkipForwardCircleOutline", component: PlaySkipForwardCircleOutline },
  { name: "PlaySkipForwardOutline", component: PlaySkipForwardOutline },
  { name: "PodiumOutline", component: PodiumOutline },
  { name: "PowerOutline", component: PowerOutline },
  { name: "PricetagOutline", component: PricetagOutline },
  { name: "PricetagsOutline", component: PricetagsOutline },
  { name: "PrintOutline", component: PrintOutline },
  { name: "PrismOutline", component: PrismOutline },
  { name: "PulseOutline", component: PulseOutline },
  { name: "PushOutline", component: PushOutline },
  { name: "QrCodeOutline", component: QrCodeOutline },
  { name: "RadioButtonOffOutline", component: RadioButtonOffOutline },
  { name: "RadioButtonOnOutline", component: RadioButtonOnOutline },
  { name: "RadioOutline", component: RadioOutline },
  { name: "RainyOutline", component: RainyOutline },
  { name: "ReaderOutline", component: ReaderOutline },
  { name: "ReceiptOutline", component: ReceiptOutline },
  { name: "RecordingOutline", component: RecordingOutline },
  { name: "RefreshCircleOutline", component: RefreshCircleOutline },
  { name: "RefreshOutline", component: RefreshOutline },
  { name: "ReloadCircleOutline", component: ReloadCircleOutline },
  { name: "ReloadOutline", component: ReloadOutline },
  { name: "RemoveCircleOutline", component: RemoveCircleOutline },
  { name: "RemoveOutline", component: RemoveOutline },
  { name: "ReorderFourOutline", component: ReorderFourOutline },
  { name: "ReorderThreeOutline", component: ReorderThreeOutline },
  { name: "ReorderTwoOutline", component: ReorderTwoOutline },
  { name: "RepeatOutline", component: RepeatOutline },
  { name: "ResizeOutline", component: ResizeOutline },
  { name: "RestaurantOutline", component: RestaurantOutline },
  { name: "ReturnDownBackOutline", component: ReturnDownBackOutline },
  { name: "ReturnDownForwardOutline", component: ReturnDownForwardOutline },
  { name: "ReturnUpBackOutline", component: ReturnUpBackOutline },
  { name: "ReturnUpForwardOutline", component: ReturnUpForwardOutline },
  { name: "RibbonOutline", component: RibbonOutline },
  { name: "RocketOutline", component: RocketOutline },
  { name: "RoseOutline", component: RoseOutline },
  { name: "SadOutline", component: SadOutline },
  { name: "SaveOutline", component: SaveOutline },
  { name: "ScaleOutline", component: ScaleOutline },
  { name: "ScanCircleOutline", component: ScanCircleOutline },
  { name: "ScanOutline", component: ScanOutline },
  { name: "SchoolOutline", component: SchoolOutline },
  { name: "SearchCircleOutline", component: SearchCircleOutline },
  { name: "SearchOutline", component: SearchOutline },
  { name: "SendOutline", component: SendOutline },
  { name: "ServerOutline", component: ServerOutline },
  { name: "SettingsOutline", component: SettingsOutline },
  { name: "ShapesOutline", component: ShapesOutline },
  { name: "ShareOutline", component: ShareOutline },
  { name: "ShareSocialOutline", component: ShareSocialOutline },
  { name: "ShieldCheckmarkOutline", component: ShieldCheckmarkOutline },
  { name: "ShieldHalfOutline", component: ShieldHalfOutline },
  { name: "ShieldOutline", component: ShieldOutline },
  { name: "ShirtOutline", component: ShirtOutline },
  { name: "ShuffleOutline", component: ShuffleOutline },
  { name: "SkullOutline", component: SkullOutline },
  { name: "SnowOutline", component: SnowOutline },
  { name: "SparklesOutline", component: SparklesOutline },
  { name: "SpeedometerOutline", component: SpeedometerOutline },
  { name: "SquareOutline", component: SquareOutline },
  { name: "StarHalfOutline", component: StarHalfOutline },
  { name: "StarOutline", component: StarOutline },
  { name: "StatsChartOutline", component: StatsChartOutline },
  { name: "StopCircleOutline", component: StopCircleOutline },
  { name: "StopOutline", component: StopOutline },
  { name: "StopwatchOutline", component: StopwatchOutline },
  { name: "StorefrontOutline", component: StorefrontOutline },
  { name: "SubwayOutline", component: SubwayOutline },
  { name: "SunnyOutline", component: SunnyOutline },
  { name: "SwapHorizontalOutline", component: SwapHorizontalOutline },
  { name: "SwapVerticalOutline", component: SwapVerticalOutline },
  { name: "SyncCircleOutline", component: SyncCircleOutline },
  { name: "SyncOutline", component: SyncOutline },
  { name: "TabletLandscapeOutline", component: TabletLandscapeOutline },
  { name: "TabletPortraitOutline", component: TabletPortraitOutline },
  { name: "TelescopeOutline", component: TelescopeOutline },
  { name: "TennisballOutline", component: TennisballOutline },
  { name: "TerminalOutline", component: TerminalOutline },
  { name: "TextOutline", component: TextOutline },
  { name: "ThermometerOutline", component: ThermometerOutline },
  { name: "ThumbsDownOutline", component: ThumbsDownOutline },
  { name: "ThumbsUpOutline", component: ThumbsUpOutline },
  { name: "ThunderstormOutline", component: ThunderstormOutline },
  { name: "TicketOutline", component: TicketOutline },
  { name: "TimeOutline", component: TimeOutline },
  { name: "TimerOutline", component: TimerOutline },
  { name: "TodayOutline", component: TodayOutline },
  { name: "ToggleOutline", component: ToggleOutline },
  { name: "TrailSignOutline", component: TrailSignOutline },
  { name: "TrainOutline", component: TrainOutline },
  { name: "TransgenderOutline", component: TransgenderOutline },
  { name: "TrashBinOutline", component: TrashBinOutline },
  { name: "TrashOutline", component: TrashOutline },
  { name: "TrendingDownOutline", component: TrendingDownOutline },
  { name: "TrendingUpOutline", component: TrendingUpOutline },
  { name: "TriangleOutline", component: TriangleOutline },
  { name: "TrophyOutline", component: TrophyOutline },
  { name: "TvOutline", component: TvOutline },
  { name: "UmbrellaOutline", component: UmbrellaOutline },
  { name: "UnlinkOutline", component: UnlinkOutline },
  { name: "VideocamOffOutline", component: VideocamOffOutline },
  { name: "VideocamOutline", component: VideocamOutline },
  { name: "VolumeHighOutline", component: VolumeHighOutline },
  { name: "VolumeLowOutline", component: VolumeLowOutline },
  { name: "VolumeMediumOutline", component: VolumeMediumOutline },
  { name: "VolumeMuteOutline", component: VolumeMuteOutline },
  { name: "VolumeOffOutline", component: VolumeOffOutline },
  { name: "WalkOutline", component: WalkOutline },
  { name: "WalletOutline", component: WalletOutline },
  { name: "WarningOutline", component: WarningOutline },
  { name: "WatchOutline", component: WatchOutline },
  { name: "WaterOutline", component: WaterOutline },
  { name: "WifiOutline", component: WifiOutline },
  { name: "WineOutline", component: WineOutline },
  { name: "WomanOutline", component: WomanOutline },
]

export const iconMap: Record<string, Component> = Object.fromEntries(
  iconCatalog.map(({ name, component }) => [name, component]),
)

export function resolveIcon(icon?: string): Component | undefined {
  return icon ? iconMap[icon] : undefined
}
