# 公共配置文件
# @author sakura
# @from sakura
server:
  servlet:
    context-path: /api
spring:
  application:
    name: sakura-boot-init-api
  messages:
    basename: messages
    encoding: UTF-8
  # 默认 dev 环境
  profiles:
    active: dev
  # 导入后端根目录下的 .env 配置文件
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:.env.${spring.profiles.active}[.properties]
      - optional:file:.env.local[.properties]
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # Redis 配置
  data:
    redis:
      database: 1
      timeout: 5000

token:
  header-name: Authorization
  header-prefix: "Bearer "
  expire-duration-seconds: 2592000
  secret-char-source: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!@#$%-+=
  secret-length: 32
  compatibility-header-enabled: true
  compatibility-header-name: "token"
  redis-token-key-prefix: "login:token:"
  redis-user-key-prefix: "login:user:"

mybatis-flex:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    normal-value-of-logic-delete: 0
    deleted-value-of-logic-delete: 1
    logic-delete-column: is_delete
  type-aliases-package: com.sakura.boot_init.infra.persistence.entity
# 微信相关
wx:
  # 微信公众平台
  mp:
    token: ${WX_MP_TOKEN:xxx}
    aesKey: ${WX_MP_AES_KEY:xxx}
    appId: ${WX_MP_APP_ID:xxx}
    secret: ${WX_MP_SECRET:xxx}
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  open:
    appId: ${WX_OPEN_APP_ID:xxx}
    appSecret: ${WX_OPEN_APP_SECRET:xxx}
# 对象存储
oss:
  enable: true
  # 对应云厂商的站点域名
  endpoint: oss-cn-shenzhen.aliyuncs.com
  # 对应云厂商桶的绑定域名
  domain: ''
  accessKey: ${OSS_ACCESS_KEY:}
  secretKey: ${OSS_SECRET_KEY:}
  # 前缀
  prefix: 'images/'
  # 存储空间名/桶名
  bucketName: sakura-init
  # 存储区域
  region: 'oss-cn-shenzhen'
  # 是否https（Y=是,N=否）
  isHttps: Y
  # 桶权限类型(0private 1public 2custom)
  accessPolicy: 1

#日志配置
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss